### ISSUE TITLE
Diagrams and Dark Mode

### ISSUE THREAD

**Issue by pkbullock** [pnp/graph-connectors-samples#25]
Hi @waldekmastykarz , 

In the sample: https://github.com/pnp/graph-connectors-samples/tree/main/samples/nodejs-typescript-food-catalog
reading through the samples and noticed in some cases the diagrams do not represent well in dark mode on GH.

Its only some of them, those with swim lanes seem fine:

![image](https://github.com/pnp/graph-connectors-samples/assets/8781041/e6d57fa5-f8db-4cdf-9d97-bdd42be38b3e)

Albeit this is a very cool sample, with the explanations and learnings around the multiple ingestion scenarios  - GREAT WORK!! Both of you @garrytrinder and @waldekmastykarz

**Comment by garrytrinder** [comment]
Thanks for letting us know @pkbullock

Unfortunately, I'm not sure if there is much we can do about this, the C4 model is currently experimental and I guess lacks support for different themes at this time. However, we should keep this in mind and maybe add a remark on the page about viewing these diagrams using dark mode. What do you think @waldekmastykarz ?

Thank you for your kind words ❤️

**Comment by waldekmastykarz** [comment]
Thank you for the kinds words @pkbullock! I think that's a great feedback for GitHub folks. Let us see if I we can find the right folks internally to get it fixed for everybody. I appreciate you letting us know ❤️

**Comment by waldekmastykarz** [comment]
Closing for now, as there's nothing that we can do about it on our end. But will update if we hear anything. Thanks again!
