### ISSUE TITLE
[nodejs-typescript-food-catalog] "resultType.json" file not exist 

### ISSUE THREAD

**Issue by formulahendry** [pnp/graph-connectors-samples#48]
In readme step 4, It need user to open "resultType.json" file, but only found "resultLayout.json" instead. 
https://github.com/pnp/graph-connectors-samples/tree/main/samples/nodejs-typescript-food-catalog#4-create-the-result-type-template
![image](https://github.com/pnp/graph-connectors-samples/assets/1050213/35af7388-7608-4ff1-ab51-b908c091e771)

cc @garrytrinder

**Comment by waldekmastykarz** [comment]
Fixed. Thank you for bringing this up
