### ISSUE TITLE
URLs in M365 Copilot citations not working on external items in graph

### ISSUE THREAD

**Issue by marnocha** [pnp/graph-connectors-samples#56]
I used the Graph Connectors API as in this sample to push items into the graph index to an external system (example: https://mydemoclient.freshservice.com/a/solutions/articles/123456789). Connector works great. I see results in SharePoint Search, I can see items in Graph Explorer. Copilot can even answer a question and provide a citation to the KB/solution articles that are in the Graph. 

The issue is that the citation links in M365 Copilot don't link to the source system. It is missing an href/url so you hover over it and click and it does nothing.

My links work fine in SharePoint search, I can navigate to the article in the external system. Links to external items from another connector work fine (using the native MS Graph connector for ServiceNow) in both search results and Copilot citations. So I don't think it is a Copilot bug. I believe the bug is missing info/documentation on what properties you need to set on an external item in the graph to make Copilot citation links work.

I've tried: url, titleUrl, accessUrl and a host of others like webdavUrl.

Has anyone else run into this issue and found a solution? Can you update this sample repo with a fix?

**Comment by waldekmastykarz** [comment]
Which sample are you referring to @marnocha?

**Comment by marnocha** [comment]
@waldekmastykarz  Specifically I used this as the starter for a connector: https://github.com/microsoftgraph/msgraph-search-connector-sample/tree/main/PartsInventoryConnector but instead of pushing parts from a CSV file, I am pushing solution articles with urls.

**Comment by marnocha** [comment]
Please keep open

**Comment by waldekmastykarz** [comment]
This sample is from a different repo. I suggest you submit the issue there so that it can be handle by the respective owner.
